# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Melcher"
license = "MIT"
licenselink = "https://github.com/jpescador/hugo-future-imperfect/blob/master/LICENSE.md"
description = "Adjusted theme for my blog - ported from hugo-future-imperfect"
homepage = "https://melcher.dev"
tags = ["blog", "responsive", "font awesome", "highlight.js", "fancybox 3", "staticman", "netlify"]
features = ["html5", "css3", "responsive"]
min_version = 0.15

[author]
  name = "Max Melcher"
  homepage = "https://melcher.dev"

# If porting an existing theme
[original]
  name = "Future Imperfect"
  homepage = "http://html5up.net/future-imperfect"
  repo = ""
